import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wingless Dreamer Publisher | Writer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Wingless Dreamer Publisher | Writer</title>
        <meta
          name="description"
          content="Discover a world of captivating stories and poetic brilliance with Wingless Dreamer. Explore a diverse publishing of genres including dulcet romance, spine-chilling horror, and gripping crime, among others. Unleash your imagination with us, where dreams take flight and extraordinary tales come alive"
        />
        <meta
          property="og:title"
          content="Wingless Dreamer Publisher | Writer"
        />
        <meta
          property="og:description"
          content="Discover a world of captivating stories and poetic brilliance with Wingless Dreamer. Explore a diverse publishing of genres including dulcet romance, spine-chilling horror, and gripping crime, among others. Unleash your imagination with us, where dreams take flight and extraordinary tales come alive"
        />
        <meta property="og:image" content="/assets/images/meta_logo.jpeg" />
        <meta property="og:url" content="https://www.winglessdreamer.com" />
        <meta property="og:site_name" content="Wingless Dreamer" />
        <meta property="og:type" content="website" />
        {/* twitter */}
        <meta
          name="twitter:title"
          content="Wingless Dreamer Publisher | Writer"
        />
        <meta
          property="twitter:image"
          content="/assets/images/meta_logo.jpeg"
        />
        <meta
          name="twitter:description"
          content="What's your story today? We welcome the world changers to our creative community wholeheartedly to get their dreams inked. Unleash the magic. Let's Read. Write. Achieve."
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        <div>
          <div className="relative">
            <div
              style={{
                backgroundImage: "url('/assets/images/home.jpeg')",
                backgroundSize: "cover",
                height: "100%",
                width: "100%",
                position: "fixed",
              }}
            >
              abcd
            </div>
          </div>
        </div>
        <header className="relative">
          <Navbar />
        </header>
        <div className="relative h-[calc(100vh-75px)] xl:h-[calc(100vh - 110px)]">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
